### ISSUE TITLE
GTAIMFPS5

### ISSUE THREAD

**Issue by MZ82020** [abduallahmohamed/Skeleton-Graph#2]
Hello, 

I have a question regarding the line in the train.py script : datasections = glob.glob('./GTAIMFPS5/*/').

GTAIMFPS5 must contain what exactly please? can you tell me how many files in total and contain what please? because I have the database but I did not understand what exactly I should choose to put.

**Comment by abduallahmohamed** [comment]
Hi,

Thanks for asking.
You can obtain the GTAIM dataset from  https://github.com/ZheC/GTA-IM-Dataset#requesting-dataset
Once you gain access to the dataset, you will find a folder with FPS5 within it. Just add this folder into the code folder. The dataloader will process from there.

**Comment by MZ82020** [comment]
Hello, 

THE FPS5 FOLDER which is in the GTA database shall I name it GTAIMFPS5 or shall I put it in GTAIMFPS5 please?

Best regards,

----- Mail original -----
De: "Abduallah Mohamed" ***@***.***>
À: "abduallahmohamed/Skeleton-Graph" ***@***.***>
Cc: "MZ82020" ***@***.***>, "Author" ***@***.***>
Envoyé: Mercredi 16 Novembre 2022 01:35:25
Objet: Re: [abduallahmohamed/Skeleton-Graph] GTAIMFPS5 (Issue #2)

Hi,

Thanks for asking.
You can obtain the GTAIM dataset from  https://github.com/ZheC/GTA-IM-Dataset#requesting-dataset
Once you gain access to the dataset, you will find a folder with FPS5 within it. Just add this folder into the code folder. The dataloader will process from there. 


-- 
Reply to this email directly or view it on GitHub:
https://github.com/abduallahmohamed/Skeleton-Graph/issues/2#issuecomment-1316086619
You are receiving this because you authored the thread.

Message ID: ***@***.***>
-- 
Bien cordialement,
Mayssa ZAIER

**Comment by abduallahmohamed** [comment]
Rename it as I recall.
------------------------------------------
Abduallah Mohamed
abduallahmohamed.com
