### ISSUE TITLE
Sequence prediction

### ISSUE THREAD

**Issue by MZ82020** [abduallahmohamed/Skeleton-Graph#4]
Hello, 

I have a question about your approach.

How many sequences did you use for the observation and then for the prediction phase for GTA dataset please?

How many frames do you use to observe and then predict for how many frames?

Best regards,

**Comment by abduallahmohamed** [comment]
For GTA-IM we used the 5 FPS version following prior works. I don't recall the FPS for the other dataset but we used the default version. 
For observation we followed prior works of observing 5 sequences then the prediction can start with at least 10 sequences based on how long you want to predict into the future. This is why you see our evaluation metrics account for different prediction horizons.

**Comment by MZ82020** [comment]
How is this procedure done? I don't understand much.. we observe 5 sequences and predict at least 10 sequences, and the fps5 folder contains just 14 sequences!

**Comment by MZ82020** [comment]
How is this procedure done? I don't understand much.. We observe 5 sequences and predict at least 10 sequences, and the FPS5 folder contains 14 sequences. How is this?

I don't have much how you did it and where it is modeled what you said in the code!

**Comment by abduallahmohamed** [comment]
The Sequences in the GTA-IM folder are already sampled. Please check the dataloader:
https://github.com/abduallahmohamed/Skeleton-Graph/blob/main/gtaimdset.py 
It creates a sliding window https://github.com/abduallahmohamed/Skeleton-Graph/blob/c6f37ec59ca9db9625f538750d690b2d1f24f27c/gtaimdset.py#L150

**Comment by MZ82020** [comment]
x, xA, y represent what please?

**Comment by abduallahmohamed** [comment]
x is the 2d input joins
xA is the adjacency matrix
y is the 3d target poses
------------------------------------------
Abduallah Mohamed
abduallahmohamed.com
