### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by MZ82020** [abduallahmohamed/Skeleton-Graph#5]
Hello, 

When I run the visualization script: CUDA_VISIBLE_DEVICES=1 python3 visualization.py --lr 0.01 --n_stgcnn 5 --n_txpcnn 11  --dataset GTA_IM --use_lrschd --num_epochs 450  --tag 1   --torso_joint 13 --eval_only 

I keep getting this error that I don't understand!
<img width="403" alt="Capture d’écran 2022-11-28 111849" src="https://user-images.githubusercontent.com/94976539/204253292-fdab147f-137f-4cdf-9297-f9275d77ea60.png">

Can you help me please? 

Best regards,

**Comment by abduallahmohamed** [comment]
This seems to be an issue in the python library 'qhull' and not our code
base issue
------------------------------------------
Abduallah Mohamed
abduallahmohamed.com
